version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    target-branch: beta
    schedule:
      interval: cron
      cronjob: "0 7 * * 0,1,3,5"
      timezone: America/New_York
    groups:
      nuget-dependencies:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /
    target-branch: beta
    schedule:
      interval: cron
      cronjob: "0 7 * * 0,1,3,5"
      timezone: America/New_York
    groups:
      cargo-dependencies:
        patterns:
          - "*"
