[package]
name = "features_test"
edition = "2024"
publish = false

[dependencies]
hub = { path = "../hub" }
anyhow = "^1.0.102"
tokio = { version = "^1.52.3", features = ["rt-multi-thread", "macros", "sync", "time", "io-util", "net"] }
serde_json = "^1.0.150"
serde_yaml_ng = "^0.10.0"
interprocess = { version = "^2.4.2", features = ["tokio"] }
uuid = { version = "^1.23.2", features = ["v4"] }
