<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\ClashMimo.Application\ClashMimo.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="$(AppName)" />
    <InternalsVisibleTo Include="ClashMimo.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="TextMateSharp" Version="2.0.4" />
    <PackageReference Include="TextMateSharp.Grammars" Version="2.0.4" />
  </ItemGroup>
</Project>
